spring: 
  profiles:
    active:
    - dev

-----

spring:  
  profiles: dev
  application:
    name: microservicecloud1-config-jrj-dev
    
-----

spring: 
  profiles: test
  application:
    name: microservicecloud1-config-jrj-test